# Generated by Django 6.0.1 on 2026-02-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_Evaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'managed': False},
        ),
    ]
